name: ci-golang-workflow-2
on: 
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - main

strategy:
  matrix:
    go: ['1.14', '1.15']

jobs: 
  check-app:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - run: go test 

      - run: go run math.go


